export const communityItems = [
  {
    id: "ethu",
    title: "ETHU",
    changedRate: -3.9,
    krOrUs: "us",
    img: "icn-ETHU.png",
    order: 1,
  },
  {
    id: "tsly",
    title: "TSLY",
    changedRate: -4.4,
    krOrUs: "us",
    img: "icn-TSLY.png",
    order: 2,
  },
  {
    id: "ast-space",
    title: "AST 스페이스모바일",
    changedRate: -11.9,
    krOrUs: "us",
    img: "icn-ASTS.png",
    order: 3,
  },
  {
    id: "webai",
    title: "위바이 글로벌",
    changedRate: 18.1,
    krOrUs: "us",
    img: "icn-NAS0WD6PX.png",
    order: 1,
  },
  {
    id: "gabf",
    title: "GABF",
    changedRate: 0.0,
    krOrUs: "us",
    img: "icn-GABF.png",
    order: 1,
  },
  {
    id: "goyoung",
    title: "고영",
    changedRate: 10.1,
    krOrUs: "kr",
    img: "icn-098460.png",
    order: 1,
  },
  {
    id: "daeyoung",
    title: "대영포장",
    changedRate: 25.7,
    krOrUs: "kr",
    img: "icn-014160.png",
    order: 2,
  },
  {
    id: "posco",
    title: "포스코DX",
    changedRate: -3.2,
    krOrUs: "kr",
    img: "icn-022100.png",
    order: 3,
  },
  {
    id: "samhyun",
    title: "삼현",
    changedRate: 6.6,
    krOrUs: "kr",
    img: "icn-437730.png",
    order: 1,
  },
  {
    id: "skhinics",
    title: "sk하이닉스",
    changedRate: -1.9,
    krOrUs: "kr",
    img: "icn-000660.png",
    order: 1,
  },
];
