export const risingCategoryItems = [
  {
    img: "shipbuilding-equipment.png",
    krOrUs: "kr",
    rank: 1,
    title: "조선기자재",
    categoryRate: 3.9,
    categoryTotal: 32,
    categoryRiseCnt: 27,
    winner: "대창솔루션",
    winRate: 18.0,
  },
  {
    img: "shipbuilding.png",
    krOrUs: "kr",
    rank: 2,
    title: "조선",
    categoryRate: 3.7,
    categoryTotal: 37,
    categoryRiseCnt: 31,
    winner: "대창솔루션",
    winRate: 18.0,
  },
  {
    img: "shipbuilding.png",
    krOrUs: "kr",
    rank: 3,
    title: "조선사",
    categoryRate: 2.9,
    categoryTotal: 6,
    categoryRiseCnt: 5,
    winner: "HD현대미포",
    winRate: 9.6,
  },
  {
    img: "power-plant-red.png",
    krOrUs: "kr",
    rank: 4,
    title: "원자력발전",
    categoryRate: 2.9,
    categoryTotal: 12,
    categoryRiseCnt: 11,
    winner: "대창솔루션",
    winRate: 18.0,
  },
  {
    img: "space-airline.png",
    krOrUs: "kr",
    rank: 5,
    title: "우주항공",
    categoryRate: 2.8,
    categoryTotal: 11,
    categoryRiseCnt: 10,
    winner: "쎄트렉아이",
    winRate: 6.9,
  },
  {
    img: "book-stacking.png",
    krOrUs: "kr",
    rank: 6,
    title: "교육출판",
    categoryRate: 1.7,
    categoryTotal: 9,
    categoryRiseCnt: 4,
    winner: "예림당",
    winRate: 16.8,
  },
  {
    img: "shipbuilding.png",
    krOrUs: "us",
    rank: 1,
    title: "조선사",
    categoryRate: 4.5,
    categoryTotal: 5,
    categoryRiseCnt: 3,
    winner: "마스터크래프트 보트 홀딩스",
    winRate: 25.2,
  },
  {
    img: "power-plant-green.png",
    krOrUs: "us",
    rank: 2,
    title: "천연가스개발",
    categoryRate: 2.8,
    categoryTotal: 60,
    categoryRiseCnt: 20,
    winner: "EON 리소시스",
    winRate: 94.1,
  },
  {
    img: "power-plant-red.png",
    krOrUs: "us",
    rank: 3,
    title: "원자력발전",
    categoryRate: 2.2,
    categoryTotal: 18,
    categoryRiseCnt: 13,
    winner: "오클로",
    winRate: 6.3,
  },
  {
    img: "steel-bolt.png",
    krOrUs: "us",
    rank: 4,
    title: "철강",
    categoryRate: 2.1,
    categoryTotal: 32,
    categoryRiseCnt: 15,
    winner: "이노베이트",
    winRate: 23.0,
  },
  {
    img: "golf.png",
    krOrUs: "us",
    rank: 5,
    title: "골프",
    categoryRate: 2.0,
    categoryTotal: 4,
    categoryRiseCnt: 2,
    winner: "삭스 파렌테 골프",
    winRate: 12.0,
  },
  {
    img: "cooper.png",
    krOrUs: "us",
    rank: 6,
    title: "구리",
    categoryRate: 1.8,
    categoryTotal: 8,
    categoryRiseCnt: 1,
    winner: "노던 다이너스티 미네랄스",
    winRate: 14.7,
  },
];
