import { v4 as uuidv4 } from "uuid";

export const sidebarInterestListItems = [
  {
    id: `${uuidv4()}`,
    img: "icn-alux.png",
    krOrUs: "us",
    title: "알럭스",
    priceWon: 4257,
    upOrDownPercent: 50,
  },
  {
    id: `${uuidv4()}`,
    img: "icn-apple.png",
    krOrUs: "us",
    title: "애플",
    priceWon: 120856,
    upOrDownPercent: 17,
  },
  {
    id: `${uuidv4()}`,
    img: "icn-aton.png",
    krOrUs: "us",
    title: "에이톤",
    priceWon: 6689,
    upOrDownPercent: 12,
  },
  {
    id: `${uuidv4()}`,
    img: "icn-azn.png",
    krOrUs: "us",
    title: "에이젠",
    priceWon: 56890,
    upOrDownPercent: 5,
  },
  {
    id: `${uuidv4()}`,
    img: "icn-ben.png",
    krOrUs: "us",
    title: "벤",
    priceWon: 9977,
    upOrDownPercent: 9,
  },
  {
    id: `${uuidv4()}`,
    img: "icn-bp.png",
    krOrUs: "us",
    title: "비피",
    priceWon: 4957,
    upOrDownPercent: 10,
  },
  {
    id: `${uuidv4()}`,
    img: "icn-byon.png",
    krOrUs: "us",
    title: "비욘",
    priceWon: 3390,
    upOrDownPercent: 8,
  },
  {
    id: `${uuidv4()}`,
    img: "icn-caliber.png",
    krOrUs: "us",
    title: "칼리버",
    priceWon: 88964,
    upOrDownPercent: 11,
  },
  {
    id: `${uuidv4()}`,
    img: "icn-cat.png",
    krOrUs: "us",
    title: "캣",
    priceWon: 98211,
    upOrDownPercent: 3,
  },
  {
    id: `${uuidv4()}`,
    img: "icn-clearone.png",
    krOrUs: "us",
    title: "클리어원",
    priceWon: 104780,
    upOrDownPercent: 7,
  },
];
