import { ISidebarRealtimeKrListItems } from "../types/types";

export const sidebarRealtimeKrListItems: ISidebarRealtimeKrListItems[] = [
  {
    id: `ecopro`,
    img: "icn-ecopro.png",
    krOrUs: "kr",
    title: "에코프로",
    priceWon: 14257,
    upOrDownPercent: 50,
  },
  {
    id: `hanhwa`,
    img: "icn-hanhwa.png",
    krOrUs: "kr",
    title: "한화",
    priceWon: 120856,
    upOrDownPercent: 17,
  },
  {
    id: `hanmi`,
    img: "icn-hanmi.png",
    krOrUs: "kr",
    title: "한미",
    priceWon: 6689,
    upOrDownPercent: 12,
  },
  {
    id: `hyundai`,
    img: "icn-hyundai.png",
    krOrUs: "kr",
    title: "현대",
    priceWon: 56890,
    upOrDownPercent: 5,
  },
  {
    id: `inbus`,
    img: "icn-inbus.png",
    krOrUs: "kr",
    title: "인버스",
    priceWon: 9977,
    upOrDownPercent: 9,
  },
  {
    id: `ionq`,
    img: "icn-ionq.png",
    krOrUs: "kr",
    title: "아이온큐",
    priceWon: 4957,
    upOrDownPercent: 10,
  },
  {
    id: `kb`,
    img: "icn-kb.png",
    krOrUs: "kr",
    title: "케이비",
    priceWon: 3390,
    upOrDownPercent: 8,
  },
  {
    id: `lg`,
    img: "icn-lg.png",
    krOrUs: "kr",
    title: "엘지",
    priceWon: 88964,
    upOrDownPercent: 11,
  },
  {
    id: `naver`,
    img: "icn-naver.png",
    krOrUs: "kr",
    title: "네이버",
    priceWon: 98211,
    upOrDownPercent: 3,
  },
  {
    id: `navi`,
    img: "icn-navi.png",
    krOrUs: "kr",
    title: "경동나비엔",
    priceWon: 104780,
    upOrDownPercent: 7,
  },
];
