export const usEtfItems = [
  {
    category: "levInv",
    order: 1,
    img: "etf2.png",
    title: "UVIX",
    subTitle: "VIX 장기선물 2배 ETF",
    price: 42940,
    changedRate: 8.9,
  },
  {
    category: "levInv",
    order: 2,
    img: "invus3.png",
    title: "SOXS",
    subTitle: "디렉시온 미국 반돛 3배 인버스 ETF",
    price: 28052,
    changedRate: 7.9,
  },
  {
    category: "levInv",
    order: 3,
    img: "etf1-5.png",
    title: "UVXY",
    subTitle: "프로셰어즈 VIX 단기선물 1.5배 ETF",
    price: 27549,
    changedRate: 7.5,
  },
  {
    category: "levInv",
    order: 4,
    img: "invus3.png",
    title: "TECS",
    subTitle: "디렉시온 기술주 3배 인버스 ETF",
    price: 66667,
    changedRate: 6.4,
  },
  {
    category: "levInv",
    order: 5,
    img: "invus3qqq.png",
    title: "SQQQ",
    subTitle: "프로셰어즈 QQQ 3배 인버스 ETF",
    price: 42078,
    changedRate: 4.8,
  },
  {
    category: "usStock",
    order: 1,
    img: "vixy.png",
    title: "VIXY",
    subTitle: "프로셰어즈 VIX 단기선물 ETF",
    price: 61867,
    changedRate: 4.8,
  },
  {
    category: "usStock",
    order: 2,
    img: "xle.png",
    title: "XLE",
    subTitle: "SPDR 미국 에너지 ETF",
    price: 131336,
    changedRate: 0.08,
  },
  {
    category: "usStock",
    order: 3,
    img: "xlv.png",
    title: "XLV",
    subTitle: "SPDR 헬스케어 ETF",
    price: 207517,
    changedRate: 0.06,
  },
  {
    category: "usStock",
    order: 4,
    img: "vnq.png",
    title: "VNQ",
    subTitle: "뱅가드 미국 부동산 ETF",
    price: 130416,
    changedRate: 0.04,
  },
  {
    category: "usStock",
    order: 5,
    img: "iwf.png",
    title: "IWF",
    subTitle: "아이셰어즈 러셀1000 성장주 ETF",
    price: 597100,
    changedRate: 0.0,
  },
  {
    category: "stockDividend",
    order: 1,
    img: "fvd.png",
    title: "FVD",
    subTitle: "퍼스트트러스트 안전배당 ETF",
    price: 63850,
    changedRate: 0.0,
  },
  {
    category: "stockDividend",
    order: 2,
    img: "sdy.png",
    title: "SDY",
    subTitle: "SPDR 배당증가기업 ETF",
    price: 192442,
    changedRate: 0.0,
  },
  {
    category: "stockDividend",
    order: 3,
    img: "hdv.png",
    title: "HDV",
    subTitle: "아이셰어즈 지속 가능 고배당 ETF",
    price: 164461,
    changedRate: 0.0,
  },
  {
    category: "stockDividend",
    order: 4,
    img: "dgrw.png",
    title: "DGRW",
    subTitle: "위즈덤트리 퀄리티 배당 성장 ETF",
    price: 120472,
    changedRate: 0.0,
  },
  {
    category: "stockDividend",
    order: 5,
    img: "nobl.png",
    title: "NOBL",
    subTitle: "프로셰어즈 배당귀족 ETF",
    price: 146368,
    changedRate: 0.0,
  },
  {
    category: "bond",
    order: 1,
    img: "green-etf.png",
    title: "TLT",
    subTitle: "아이셰어즈 미국 초장기 국채 ETF",
    price: 125990,
    changedRate: 0.5,
  },
  {
    category: "bond",
    order: 2,
    img: "green-etf.png",
    title: "TIP",
    subTitle: "아이셰어즈 미국 물가채 ETF",
    price: 154387,
    changedRate: 0.0,
  },
  {
    category: "bond",
    order: 3,
    img: "green-etf.png",
    title: "HYG",
    subTitle: "아이셰어즈 투기등급 회사채 ETF",
    price: 114608,
    changedRate: 0.0,
  },
  {
    category: "bond",
    order: 4,
    img: "olive-etf.png",
    title: "BIL",
    subTitle: "SPDR 초단기 국채 ETF",
    price: 131767,
    changedRate: 0.0,
  },
  {
    category: "bond",
    order: 5,
    img: "olive-etf.png",
    title: "BWX",
    subTitle: "SPDR 블룸버그 단기채 ETF",
    price: 30897,
    changedRate: 0.0,
  },
  {
    category: "material",
    order: 1,
    img: "pplt.png",
    title: "PPLT",
    subTitle: "에버딘 백금 ETF",
    price: 124927,
    changedRate: 0.05,
  },
  {
    category: "material",
    order: 2,
    img: "zsb.png",
    title: "ZSB",
    subTitle: "USCF 지속 가능 배터리 금속 전략 펀드",
    price: 18869,
    changedRate: 0.0,
  },
  {
    category: "material",
    order: 3,
    img: "corn.png",
    title: "CORN",
    subTitle: "투크리움 옥수수 ETF",
    price: 28397,
    changedRate: 0.0,
  },
  {
    category: "material",
    order: 4,
    img: "soyb.png",
    title: "SOYB",
    subTitle: "투크리움 콩 ETF",
    price: 31975,
    changedRate: 0.0,
  },
  {
    category: "material",
    order: 5,
    img: "weat.png",
    title: "WEAT",
    subTitle: "투크리움 밀 ETF",
    price: 6955,
    changedRate: 0.0,
  },
];
